language: node_js
node_js:
  - "8"

install:
  - cd kmp/client
  - npm install
  - cd ..
  - npm install
  - npm install -g ganache-cli
  - npm install -g truffle

before_runcoverage:
  - testrpc > /dev/null &
  - sleep 5

runcoverage:
  - cd kmp
  - npm run coverage && cat coverage/lcov.info | coveralls