language: node_js
node_js:
  - "8"

install:
  - cd kmp/client
  - npm install
  - cd ..
  - npm install
  - npm install -g ganache-cli
  - npm install -g truffle

script:
  - ganache-cli &
  - sleep 5
  - truffle test


before_script:
  - testrpc > /dev/null &
  - sleep 5

after_script:
  - npm run coverage 
  - ../publishCoverage.sh

deploy:
  provider: heroku
  api_key:
    secure: "d180cd52-ee50-42cd-9b8b-9cd049ab21b5"
  app: kmpblockchain
