language: node_js
  - "8"

before_script:
  - cd kmp/client
  - npm install
  - cd ..
  - npm install -g ganache-cli
  - npm install -g truffle


script:
  - ganache-cli &
  - sleep 5
  - truffle test
