language: node_js
node_js:
  - "8"

install:
  - cd kmp/client
  - npm install
  - cd ..
  - npm install
  - npm install -g ganache-cli
  - npm install -g truffle

script:
  - ganache-cli &
  - sleep 5
  - truffle test


before_script:
  - testrpc > /dev/null &
  - sleep 5

after_script:
  - "travis_wait 30 sleep 1800 &"
  - curl -o ./kmp/node_modules/solidity-parser-sc/build/parser.js https://raw.githubusercontent.com/maxsam4/solidity-parser/solidity-0.5/build/parser.js
  - npm run coverage --prefix kmp

before_deploy:
  - cd ..

deploy:
  provider: heroku
  api_key:
    secure: "d180cd52-ee50-42cd-9b8b-9cd049ab21b5"
  app: kmpblockchain
